### ISSUE TITLE
Messages sometimes logs twice 

### ISSUE THREAD

**Issue by lucas19961** [gempir/justlog#186]
With the new image Messages sometimes log twice. Fix is a restart of the conatainer. What can i do to fix it permanent ?

**Comment by gempir** [comment]
What commit are you on

**Comment by gempir** [comment]
Made a hacky fix 32254856334a6d557f26a2a98ed065df356d0f5c

For 3 seconds we keep all ids of messages and only track each once. Should get rid of all duplicates. Except for clearchat messages those sadly have no id I think. so i can't easily do the same with them

**Comment by lucas19961** [comment]
i think this is fixed with this commit

**Comment by lucas19961** [comment]
nvm

**Comment by gempir** [comment]
Any more details? I don't see how this is possible to be not fixed. 

(old messages would not magically get fixed)

**Comment by lucas19961** [comment]
I re-downloaded the dockerimage and the messages are still being logged 2 times. the instance runs only once. I have also tested it on another system myself error

**Comment by gempir** [comment]
Are you sure you are on the latest image? I just tested it even increased the rejoin loop frequency to 1 minute. I never had a double message

**Comment by lucas19961** [comment]
ghcr.io/gempir/justlog   latest    30ee89294a7d   3 hours ago    24.1MB this is my image 

and the messages are duplicated. I dont now what is my fault 
![opera_2MBXy1EU12](https://user-images.githubusercontent.com/17136546/211221242-0ac21acc-2350-44ed-80e2-28bd00c96641.png)

**Comment by gempir** [comment]
Can you post the raw output? I need to see the message ids

**Comment by lucas19961** [comment]
It works now. I guess my image was broken. I redownloaded the image and now it workes
